import { ITypes } from "../helpers/interfaces";

export const types: ITypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  USER_LOADED: "USER_LOADED",
  USERS_LOADED: "USERS_LOADED",
  LOAD_USERS_ERROR: "LOAD_USERS_ERROR",
  AUTH_ERROR: "AUTH_ERROR",
  LOG_OUT: "LOG_OUT",
  MESSAGES_LOADED: "MESSAGES_LOADED",
  MESSAGES_ERROR: "MESSAGES_ERROR",
};
